### ISSUE TITLE
Installing Big Sur on a Razer blade 15 base 2021 with samsung pm981a

### ISSUE THREAD

**Issue by medpar** [bilibili20001/RazerBlade15-Base-Model-Hackintosh#1]
I am trying to install macOS Big sur on my razer blade 15 base 2021, but the installer keeps freezing at 13 minutes left. It seems that my ssd drive, the samsung pm981a may be causing that problem, even when nvmefix readme says it is already compatible with that drive. I've used OpenCore with dortania's guide. Any suggestion on how to install macOS without having to switch the drive?

**Comment by ssr20001** [comment]
Maybe you can try this: https://bbs.pcbeta.com/viewthread-1867021-1-1.html
1. Install macOS on another drive
2. Delete snapshot in recovery mode to unlock SLE
3. Add Nvme patch in OpenCore
4. Backup macOS and restore it on your pm981a
[PM981a.zip](https://github.com/bilibili20001/RazerBlade15-Base-Model-Hackintosh/files/7795791/PM981a.zip)
