### ISSUE TITLE
External monitor on razer blade 15

### ISSUE THREAD

**Issue by medpar** [bilibili20001/RazerBlade15-Base-Model-Hackintosh#2]
After successfully setting up my hackintosh with macos big sur, I need to connect an external monitor to my razer blade 15. I am aware that both the HDMI and usb-c thunderbolt ports are connected to the nvidia graphics card. However, I would like to find some solution other than buying a displaylink device, as these are very expensive and hard to get in my country.
Is there any way to patch the device to get the intel graphics out of the hdmi or usb-c port?

**Comment by ssr20001** [comment]
The HDMI port is linked to GPU. While the Thunderbolt 3 port ain't. So you can try output via Thunderbolt 3. The patch should be similar to some other 10750H laptops.
